stages:
  - package
  - deploy

package:
  stage: package
  image: alpine:latest
  script:
    - apk add --no-cache git jq zip
    - git fetch --tags
    - zip -r StatusTracker-$CI_COMMIT_TAG.zip *.lua *.toc -x "*.git*"
    - echo $CURSEFORGE_TOKEN > curseforge_token.txt

    # Create metadata.json with changelog (using a multi-line command array for clarity)
    - |
        CHANGELOG=$(git log --pretty=format:'%h - %s' "$(git describe --tags --abbrev=0)..HEAD")
        cat > metadata.json <<EOF
        {
          "changelog": "$CHANGELOG",
          "gameVersions": ["11.0.0", "11.0.2"],
          "releaseType": "alpha"
        }
        EOF

  artifacts:
    paths:
      - StatusTracker-$CI_COMMIT_TAG.zip
      - curseforge_token.txt
      - metadata.json
  only:
    - tags

deploy:
  stage: deploy
  image: ruby:3.1-alpine
  before_script:
    - apk add --update curl jq
  script:
    - echo "Deploying tag $CI_COMMIT_TAG"
    - UPLOAD_URL="https://wow.curseforge.com/api/projects/$CURSEFORGE_PROJECT_ID/upload-file"
    - METADATA=$(jq -c . metadata.json)
    - | # Use a multiline string (>) to preserve formatting for the curl command
        curl -H "X-API-Token: $(cat curseforge_token.txt)" \
             -F "metadata=$METADATA" \
             -F "file=@StatusTracker-$CI_COMMIT_TAG.zip" \
             "$UPLOAD_URL" # Quote the URL for robustness
  dependencies:
    - package
  only:
    - tags
