name: publish_stable

on:
  push:
    tags-ignore:
      - "**-alpha-**"
      - "**-beta-**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the latest version
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Auto Packaging
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Upload to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: StatusTracker
          path: .release/*.zip
